[package]
name = "example_link"
version = "0.1.0"
edition = "2024"

[dependencies]
example_array = { version = "0.1.0", path = "../example_array" }
linkme = "0.3.35"
tokio = { version = "1.48.0", features = ["rt", "macros", "rt-multi-thread", "time"] }
